### ISSUE TITLE
Add Anchors to Runtime Spec 

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/runtime-spec#634]
By adding anchors to the spec, we enable tools to reference specific spec sections, sub-sections, bullets, list items, etc. 
- [x] bundle.md #612 
- [ ] config-linux.md #635
- [x] config-solaris.md #636
- [x] config-windows.md #637
- [ ] config.md
- [x] glossary.md #638
- [x] principles.md #639
- [x] runtime-Linux.md #640
- [ ] runtime.md #614
- [ ] spec.md
- [ ] style.md

**Comment by jlbutler** [comment]
@RobDolinMS do you have PRs for the remaining anchor adds? If not and this is something we still need, I'd be willing to whack them up.

**Comment by wking** [comment]
On Wed, Nov 30, 2016 at 03:09:59PM -0800, Rob Dolin (MSFT) wrote:
> By adding anchors to the spec, we enable tools to reference specific
> spec sections, sub-sections, bullets, list items, etc.

Should we re-open this?  For example, #614 was adding anchors to
runtime.md bullets [1] so you could link to specific properties
(e.g. [2]).  #614 was closed because it needed a rebase and the
sign-off was broken [3], and then this issue was closed by #707, which
added anchors to the sections [4], but not to bullets and list items.
So there's currently no way to link to the ociVersion entry in the
state JSON declaration outside of GitHub's blame UI [5].

[1]: https://github.com/opencontainers/runtime-spec/pull/614/files#diff-b84a8d65d8ed53f4794cd2db7e8ea731R12
[2]: https://github.com/RobDolinMS/runtime-spec/blob/6b9ae99776bb6785aab7c1be5b450bbff2517d61/runtime.md#stateOciVersion
[3]: https://github.com/opencontainers/runtime-spec/pull/614#issuecomment-277115379
[4]: https://github.com/opencontainers/runtime-spec/pull/707/files#diff-b84a8d65d8ed53f4794cd2db7e8ea731L8
[5]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0/runtime.md#L12
